spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGODB_URL}
  cloud:
    openfeign:
      image-service: ${IMAGE_SERVICE_URL}
      client:
        config:
          default:
            connect-timeout: 10000
            read-timeout: 30000
            logger-level: full
